export const questions = [
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'geography',
    question: 'Where would you be if you were standing on the Spanish Steps?',
    correct_answer: 'Rome',
    incorrect_answers: ['Paris', 'Madrid', 'London'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'geography',
    question: "Rome is known as 'The Eternal City'.",
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'geography',
    question: 'Mount Kilimanjaro is located in Tanzania.',
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'geography',
    question: 'Halloween originated as an ancient Irish festival.',
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'geography',
    question: 'What is the largest Spanish-speaking city in the world?',
    correct_answer: 'Mexico City',
    incorrect_answers: ['Buenos Aires', 'Madrid', 'Lima'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'geography',
    question: 'Sweden has the most islands of any country in the world.',
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'geography',
    question: "A 'bottle-o' in Australia refers to a liquor store.",
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'geography',
    question: "In which U.S. state is the country's busiest airport located?",
    correct_answer: 'Georgia',
    incorrect_answers: ['California', 'New York', 'Texas'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'geography',
    question: 'Africa is the only continent with land in all four hemispheres.',
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'geography',
    question: 'Which river flows through the Grand Canyon?',
    correct_answer: 'Colorado River',
    incorrect_answers: ['Amazon River', 'Mississippi River', 'Nile River'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'geography',
    question: 'Where is Angel Falls, the world’s largest waterfall, located?',
    correct_answer: 'Venezuela',
    incorrect_answers: ['Brazil', 'Norway', 'Australia'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'geography',
    question: 'Holland is a region in the Netherlands.',
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'geography',
    question: 'What are the five Great Lakes?',
    correct_answer: 'Superior, Michigan, Huron, Erie, and Ontario',
    incorrect_answers: [
      'Black Sea, Red Sea, Caspian Sea, White Sea, Yellow Sea',
      'Caspian Sea, Aral Sea, Black Sea, Adriatic Sea',
      'Lake Baikal, Lake Victoria, Lake Tahoe, Lake Michigan, Lake Superior',
    ],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'geography',
    question: 'How many European capitals does the Danube flow through?',
    correct_answer: '4',
    incorrect_answers: ['2', '3', '5'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'geography',
    question: 'What is the capital of Canada?',
    correct_answer: 'Ottawa',
    incorrect_answers: ['Toronto', 'Montreal', 'Vancouver'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'geography',
    question: 'In what capital would you find The Little Mermaid statue?',
    correct_answer: 'Copenhagen',
    incorrect_answers: ['Stockholm', 'Amsterdam', 'Berlin'],
  },
  {
    type: 'boolean',
    difficulty: 'hard',
    category: 'geography',
    question: 'Nepal is the only country whose flag is not a quadrilateral.',
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'geography',
    question: 'How many stars are on the Chinese flag?',
    correct_answer: '5',
    incorrect_answers: ['4', '6', '7'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'geography',
    question: 'How many colors are used in the South African flag?',
    correct_answer: '6',
    incorrect_answers: ['5', '7', '4'],
  },
  {
    type: 'multiple',
    difficulty: 'easy',
    category: 'geography',
    question: 'What colors is the flag of the United Nations?',
    correct_answer: 'Blue and white',
    incorrect_answers: ['Red and white', 'Blue and yellow', 'Green and white'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'geography',
    question: 'What country features a shipwreck on its national flag?',
    correct_answer: 'Bermuda',
    incorrect_answers: ['Barbados', 'Malta', 'Portugal'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'geography',
    question: 'In what country is the Chernobyl nuclear plant located?',
    correct_answer: 'Ukraine',
    incorrect_answers: ['Russia', 'Belarus', 'Poland'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'geography',
    question: 'Which is the only sea without any coastlines?',
    correct_answer: 'The Sargasso Sea',
    incorrect_answers: ['Mediterranean Sea', 'Baltic Sea', 'Caspian Sea'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'geography',
    question: 'What mountain range separates Europe and Asia?',
    correct_answer: 'The Ural Mountains',
    incorrect_answers: ['The Alps', 'The Pyrenees', 'The Carpathians'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'geography',
    question: 'The Ural Mountains separate Europe and Asia.',
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'boolean',
    difficulty: 'easy',
    category: 'geography',
    question: 'The Amazon Rainforest is the largest rainforest in the world.',
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'boolean',
    difficulty: 'medium',
    category: 'geography',
    question: 'Japan is made up of over 6,000 islands.',
    correct_answer: 'true',
    incorrect_answers: ['false'],
  },
  {
    type: 'multiple',
    difficulty: 'medium',
    category: 'geography',
    question: 'What is the smallest U.S. state by area?',
    correct_answer: 'Rhode Island',
    incorrect_answers: ['Delaware', 'Connecticut', 'Hawaii'],
  },
  {
    type: 'multiple',
    difficulty: 'hard',
    category: 'geography',
    question: 'What is the tallest type of tree?',
    correct_answer: 'Redwood',
    incorrect_answers: ['Pine', 'Oak', 'Cypress'],
  },
];
